### ISSUE TITLE
roslaunch以后rviz一片空白

### ISSUE THREAD

**Issue by petertheprocess** [ZJU-FAST-Lab/ego-planner-swarm#14]
roslaunch ego_planner simple_run.launch之后出现了空白的rviz，飞机模型和轨迹都没有显示。
终端一直报
[FSM]: state: INIT
no odom.
wait for goal or trigger.
请问这是少安了什么依赖吗？我是ubuntu20.04
![image](https://user-images.githubusercontent.com/30321432/130309316-0704f377-65ad-4bee-8fa7-f18350d9c0f5.png)

**Comment by petertheprocess** [comment]
不好意思，已经解决了，是我ros的ip和hosts错乱了，所以所有的topic都没发布出来。

**Comment by Marco-Yang** [comment]
> 你好，请问ros的IP和hosts错乱的问题如何解决的，期待您的回复

**Comment by bcwww** [comment]
> 不好意思，已经解决了，是我ros的ip和hosts错乱了，所以所有的topic都没发布出来。

你好，我也遇到了相同的問題，想請問是如何解決的呢?
期待您的回覆
