### ISSUE TITLE
How to define the drone footprint for collision free path planning?

### ISSUE THREAD

**Issue by Pallav1299** [ZJU-FAST-Lab/ego-planner-swarm#17]
Thanks for the great work. Are we defining the drone footprint for collision free path planning in ego-planner-swarm? If yes, how? Is there any parameter for the same?
Do we have to configure the obstacle inflation to control the same?

In general, a brief documentation of the planner params would help a lot.

**Comment by bigsuperZZZX** [comment]
In fact, we use a point model and the obstacle inflation is the right way to define the "footprint".

**Comment by Pallav1299** [comment]
@bigsuperZZZX, thanks for the answer.
