### ISSUE TITLE
perhaps this function should be pos2Pixel(...) rather than pos2Depth(...)?????

### ISSUE THREAD

**Issue by tiemuhua** [ZJU-FAST-Lab/ego-planner-swarm#2]
![image](https://user-images.githubusercontent.com/46767782/103440031-4bb97380-4c7d-11eb-98f2-87f32ff871d3.png)

**Comment by zhujiangchao** [comment]
My original meaning here was the depth image, didn't expect it would cause ambiguity. Thank you for your comment.
