### ISSUE TITLE
What are different branches of this project responsible for?

### ISSUE THREAD

**Issue by shubham-shahh** [ZJU-FAST-Lab/ego-planner-swarm#22]
Hi, I saw a few branches along with the master branch, what are different branches responsible for?

**Comment by bigsuperZZZX** [comment]
Other branches are just some middle-term developments, which are pushed to github server for collaborative coding. Users don't need to pay attention to them.

**Comment by shubham-shahh** [comment]
> Other branches are just some middle-term developments, which are pushed to github server for collaborative coding. Users don't need to pay attention to them.

okay, thanks for the response
