### ISSUE TITLE
Some questions about reboundreplan function

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/ego-planner-swarm#29]
I read the code about reboundreplan function and have some confusion:
This project doesn't use ESDF map, instead of base point and vector. But it only finds the {p,v} pair within collision segments consisted of control points. Sometimes the generated trajs may be too close to some obstacles, because collision-free optimal problem doesn't care about the segment which is close to obstacles but no happen collision. I want to improve this by increasing inflation. It's effective but not changes this problem fundamentally. I want to know whether your lab try to solve the problem and how to do?

**Comment by bigsuperZZZX** [comment]
In our perspective, collision avoidance is a strict constraint, and thus should be strictly satisfied by appropriate inflation.
