### ISSUE TITLE
when you avoid obstacles, how do you ensure that the plane will not collide

### ISSUE THREAD

**Issue by 001zwzwzw** [ZJU-FAST-Lab/ego-planner-swarm#30]
hello!I want to know the method that when you avoid obstacles, how do you ensure that the plane will not collide

**Comment by 001zwzwzw** [comment]
@ZhepeiWang

**Comment by 001zwzwzw** [comment]
@ZhepeiWang @USTfgaoaa i need your help!Thanks !

**Comment by ZhepeiWang** [comment]
@bigsuperZZZX

**Comment by bigsuperZZZX** [comment]
The plane itself does not need to be strictly collision-free. It just provides the information to push the only control point that generates this plane away from obstacles. Whether the final trajectory is collision-free is guaranteed by a post-check procedure.

**Comment by 001zwzwzw** [comment]
> The plane itself does not need to be strictly collision-free. It just provides the information to push the only control point that generates this plane away from obstacles. Whether the final trajectory is collision-free is guaranteed by a post-check procedure.

 @bigsuperZZZX  Thanks very much ! than,i want to ask the problem that every trajectories of drone 0~9 are known other drones?For example the trajectory of drone 0 is shared with other drones like drone 1~9?how do you achieve them in procedure

**Comment by 001zwzwzw** [comment]
@bigsuperZZZX Thanks very much ! then,i want to ask the problem that every trajectories of drone 0-9 are known other drones?For example the trajectory of drone 0 is known by other drones like drone 1-9? how do you achieve them in procedure

**Comment by bigsuperZZZX** [comment]
Everyone knows others' trajectories via a wireless broadcasting network.

**Comment by 001zwzwzw** [comment]
@bigsuperZZZX  Wether this method will bring a communication pressure in real test of UAV-swarm ?thanks!

**Comment by bigsuperZZZX** [comment]
It's hard to tell since wireless communication quality is affected by many factors. 
According to our tests, a swarm of ten drones enjoys the WiFi connection.
We haven't tested more agents as we have 10 drones in total.

**Comment by 001zwzwzw** [comment]
@bigsuperZZZX  ok I learn more knowledge from you! Thank you, senior brother!
about hardware equipment,do you use two camera to run ego-planner? one provides depth image,another provides position information?

**Comment by 001zwzwzw** [comment]
for example D435i and T265?

**Comment by bigsuperZZZX** [comment]
We use D435 only with vins which positions our drones.

**Comment by 001zwzwzw** [comment]
yea! I konw ! Thank you very much

**Comment by 001zwzwzw** [comment]
salute！thank you very mucn
