### ISSUE TITLE
Terminal cost

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/ego-planner-swarm#31]
In ego-planner, rebound cost only considers smoothness,distance and feasibility.In ego-swarm, terminal cost and swarm cost are added. I understand the swarm cost function, but don't know the usage of terminal cost. It seems that it will help terminal 3 points be closed to local target point, but ego-planner doesn't use it which also works well.

**Comment by bigsuperZZZX** [comment]
Terminal cost is adopted to expand the solution space so that a potentially better solution may be found.

**Comment by dssdyx** [comment]
> Terminal cost is adopted to expand the solution space so that a potentially better solution may be found.

Thank you for your answer!
