### ISSUE TITLE
Swarm configuration

### ISSUE THREAD

**Issue by shubham-shahh** [ZJU-FAST-Lab/ego-planner-swarm#32]
Hi @bigsuperZZZX,
To use this package for the swarm, do we need to run this package on each drone, or this package will run on one drone, listen to other drone's odometry and publish trajectories for other drones.

Thanks

**Comment by bigsuperZZZX** [comment]
This package runs on each drone.

**Comment by shubham-shahh** [comment]
> This package runs on each drone.

okay, thanks
