### ISSUE TITLE
Question about the effect of localization drift and stabilization in planner and controller

### ISSUE THREAD

**Issue by dssdyx** [ZJU-FAST-Lab/ego-planner-swarm#37]
大佬你好，想请教一个问题，就是定位模块的漂移会对实际实验的避障效果带来影响么？
我个人的想法使如果定位模块是视觉定位那种，漂移只是慢慢累积的，每帧间的相对定位还是稳定变化的，那么应该不会对规划和控制造成什么影响吧。我有这个想法是因为，看到在规划器里，定位odom信息主要是用在更新占据地图上，而不是规划轨迹里，因为除了一开始，大部分时间轨迹规划的起点都是上一条轨迹在该时刻的状态，而不是当前的定位，我就想这样如果一直不触发GEN_NEW_TRAJ的状态，然后定位越来越漂，是否会对避障起到影响。但是又想了想，控制器应该是一直趋于把当前状态拉向和期望轨迹差不多，所以就算定位漂也没关系，同时轨迹自己也会根据占据地图去刷新，而占据地图本身是相对漂了的定位投影的，所以定位漂了对避障是没有实际影响的。
   但是如果定位模块精度比较低，像GPS那样，会在定位的真实值附近来回跳变，会对planner和controller有影响么，如果有，对谁的影响比较大呢？希望大佬可以帮忙解答，实在是想不明白。

**Comment by bigsuperZZZX** [comment]
定位模块的缓慢漂移不会影响避障，如果是GPS这种跳变，会影响避障导致事故

**Comment by dssdyx** [comment]
> 定位模块的缓慢漂移不会影响避障，如果是GPS这种跳变，会影响避障导致事故

Thx!!
