### ISSUE TITLE
Potential minor bug in depth map projectection?

### ISSUE THREAD

**Issue by zyayoung** [ZJU-FAST-Lab/ego-planner-swarm#38]
Thanks for your great work!

https://github.com/ZJU-FAST-Lab/ego-planner-swarm/blob/8da8a01e7d01a9977306aaf2922cf85a1a3de71e/src/planner/plan_env/src/grid_map.cpp#L275-L285

To the best of my understanding, the code here (L282-L285) should function as `if (depth == 0) depth = mp_.max_ray_length_ + 0.1;`.
However, the pointer `row_ptr` is incremented in L276 so (*row_ptr) gets the depth of the next pixel.

I'm wondering if this is a design choice or an implementation issue. Thanks!

**Comment by bigsuperZZZX** [comment]
L284 will never function. It's just an implementation issue.
