### ISSUE TITLE
真机复现问题

### ISSUE THREAD

**Issue by HaoyangWang0428** [ZJU-FAST-Lab/ego-planner-swarm#39]
作者您好，我有幸在b站看到了贵实验室上传的ego-planner真机实验视频，并成功完成了复现。在学习ego-planner-swarm代码的过程中，我开始思考能否在多机上复现该算法。在此希望作者能够就如何复现指点一二。最后，感谢您为社区做的贡献，如能收到您的回复，我将不胜感激。

**Comment by zyayoung** [comment]
我想知道真机的global odometry是怎么实现的？
不知道作者是否能简单介绍下真机部署的流程。

**Comment by zyayoung** [comment]
Localization Drift Compensation这部分的代码也是开源的吗 😢 
还烦请作者指一下路，不胜感激

**Comment by bigsuperZZZX** [comment]
这些部分可以参考我们的另一篇文章和它的相关代码，那里写得比较清楚
https://www.science.org/doi/10.1126/scirobotics.abm5954
