### ISSUE TITLE
Real world vision SLAM

### ISSUE THREAD

**Issue by DaSheng1998** [ZJU-FAST-Lab/ego-planner-swarm#4]
你们工程当中在仿真中是没有视觉SLAM的部分吗？ 如果移植真是无人机的话，是不是要完成视觉定位的部分

**Comment by bigsuperZZZX** [comment]
对，跑实物还需要一大堆配套模块

**Comment by DaSheng1998** [comment]
> 对，跑实物还需要一大堆配套模块

你们实验室是在浙江大学吗？？ 有没有去浙大参观和交流的机会呢？

**Comment by bigsuperZZZX** [comment]
是的浙大的，如果希望来交流的话请联系高飞老师 [https://ustfei.com/](https://ustfei.com/)

**Comment by bigsuperZZZX** [comment]
如果没有别的问题了，请关闭这个issue，谢谢
