### ISSUE TITLE
Terminal point of the current trajectory is in obstacle, skip this planning

### ISSUE THREAD

**Issue by robin-shaun** [ZJU-FAST-Lab/ego-planner-swarm#5]
Hello, I sometimes meet continuous warning `terminal point of the current trajectory is in obstacle, skip this planning`  in my PX4 SITL Simulation and the UAV will stop. I think this will happen when there's no solution to reach the goal, but indeed when this happens no obstacle is in front of the UAV.

In most cases, ego_planner works quite well. Thanks for the wonderful work.

![image](https://user-images.githubusercontent.com/20561850/113308229-8bedc800-9338-11eb-84c3-83cbe8e0a594.png)

![image](https://user-images.githubusercontent.com/20561850/113308332-a45de280-9338-11eb-9605-d076fd21724b.png)

**Comment by bigsuperZZZX** [comment]
If no obstacle is in front of the UAV while this error keeps reporting, then maybe the given goal is outside the global map, or the goal is insider the inflated obstacles. Please check that.

**Comment by robin-shaun** [comment]
Is the global map size given by `  <arg name="map_size_x"/>
  <arg name="map_size_y"/>
  <arg name="map_size_z"/>` in  [here](https://github.com/ZJU-FAST-Lab/ego-planner-swarm/blob/master/src/planner/plan_manage/launch/run_in_sim.launch)?

**Comment by bigsuperZZZX** [comment]
Yes. The map region is [-map_size_x/2, map_size_x/2], [-map_size_y/2, map_size_y/2], [[ground_height](https://github.com/ZJU-FAST-Lab/ego-planner-swarm/blob/5ddc525bfb83f6e015c630e44223c6296c755376/src/planner/plan_manage/launch/advanced_param.xml#L97), map_size_z-ground_height].

**Comment by robin-shaun** [comment]
OK, I'll try it.

**Comment by bigsuperZZZX** [comment]
Hello, if you have no other questions, please close this issue.
