### ISSUE TITLE
关于仿真中的通信问题

### ISSUE THREAD

**Issue by cgp1997** [ZJU-FAST-Lab/ego-planner-swarm#72]
在运行simple_run.launch 中好像并没有使用到bridge.launch,请问在仿真中该如何配置，才能正确启动rosmsg_tcp_bridge，实现udp和tcp的连接。

**Comment by ChenYihan618** [comment]
您好，请问这个问题您是怎么解决的呢？

**Comment by cgp1997** [comment]
这个文件好像是在实飞时才用到，仿真里面通过节点间通信和广播去模拟的tcp和udp

**Comment by ChenYihan618** [comment]
明白了，感谢！
